import os
from fastapi import APIRouter, UploadFile, File, HTTPException
from pydantic import BaseModel
from langchain_core.messages import AIMessage, ToolMessage
from rag.loader import load_document
from rag.chunking import split_documents
from rag.vectorstore import add_documents_to_store

from agent.agent import get_agent_executor
from memory.memory import get_session_history

router = APIRouter()

UPLOAD_FOLDER = "documents"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

# Pydantic schema enforcing incoming JSON shape validation
class ChatRequest(BaseModel):
    session_id: str
    message: str


@router.post("/documents/upload")
async def upload_document(file: UploadFile = File(...)):
    """Asynchronously streams incoming file attachments to storage and registers them to ChromaDB."""
    if not file.filename:
        raise HTTPException(status_code=400, detail="Uploaded file lacks a valid name structure.")
        
    path = os.path.join(UPLOAD_FOLDER, file.filename)
    
    try:
        # Write binary stream down cleanly
        with open(path, "wb") as buffer:
            # Note: For production large payloads, async chunk reading is ideal, 
            # but file.file works safely here.
            buffer.write(file.file.read())

        # Procedural execution pipeline chain
        docs = load_document(path)
        chunks = split_documents(docs)
        add_documents_to_store(chunks)

        return {
            "filename": file.filename,
            "status": "uploaded"
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"File processing pipeline failed: {str(e)}")


@router.get("/documents")
def list_documents():
    """Lists every raw knowledge source file currently present inside the local repository upload cache."""
    if not os.path.exists(UPLOAD_FOLDER):
        return []
    return os.listdir(UPLOAD_FOLDER)


@router.post("/chat")
def chat(request: ChatRequest):
    """Processes message requests through the latest official LangChain agent harness framework."""
    # 1. Fetch local session memory history for tracking verification
    history = get_session_history(request.session_id)

    # 2. Store incoming query string locally
    history.add_user_message(request.message)

    # 3. Pull the active agent runtime harness
    agent = get_agent_executor()
    
    # 4. Enforce conversation persistence by passing the session_id as the thread_id
    config = {"configurable": {"thread_id": request.session_id}}
    
    try:
        # 5. Invoke the agent passing standard message structures and configuration keys
        result = agent.invoke(
            {"messages": [{"role": "user", "content": request.message}]},
            config=config
        )
        print(f"Agent execution result: {result}")

        # 6. Pull the final text statement out from the message stream array
        output_messages = result.get("messages", [])
        if not output_messages:
            raise HTTPException(status_code=500, detail="Agent structure returned an empty execution path.")
            
        final_answer_text = output_messages[-1].content
        
        # 7. Persist AI answer text back to local session history
        history.add_ai_message(final_answer_text)

        # 8. Parse out the tool steps directly from the runtime state logs
        clean_reasoning_steps = []
        for msg in output_messages:
            if isinstance(msg, AIMessage) and getattr(msg, "tool_calls", None):
                for tool_call in msg.tool_calls:
                    clean_reasoning_steps.append({
                        # CRITICAL FIX: Save the unique ID generated by the LLM for this specific tool call
                        "tool_call_id": tool_call.get("id"), 
                        "tool_activated": tool_call.get("name", "Unknown Tool"),
                        "tool_input": str(tool_call.get("args", "")),
                        "thought_log": msg.additional_kwargs.get("reasoning_content", "") or getattr(msg, "content", "") or "Evaluating tool execution logic.",
                        "tool_output_received": "Awaiting response payload..."
                    })
            
            # Map the corresponding tool result message to the last tracked tool activation step
            elif isinstance(msg, ToolMessage):
        # Look through our collected steps to find the one matching this specific tool_call_id
                for step in clean_reasoning_steps:
                    if step.get("tool_call_id") == msg.tool_call_id:
                        step["tool_output_received"] = str(msg.content)
                        break
        for step in clean_reasoning_steps:
            if "tool_call_id" in step:
                del step["tool_call_id"]
        return {
            "answer": final_answer_text,
            "reasoning": clean_reasoning_steps
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Agent execution path failure: {str(e)}")


@router.get("/chat/{session_id}/history")
def get_chat_history(session_id: str):
    """Retrieves standard history structures mapped directly to the active session index string."""
    chat_history = get_session_history(session_id)
    return [
        {
            "type": msg.type,
            "content": msg.content
        }
        for msg in chat_history.messages
    ]
